services:
  - type: web
    name: mmm-platform-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mmm-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: mmm-db
    plan: free
    databaseName: mmm_platform
